pipeline {
    agent any
    stages {
        stage('Checkout') { 
            steps {
                git 'https://github.com/jishnugopalan/simple-java-maven-app.git'
            }
        }
        stage('Build') { 
            steps {
                sh 'mvn clean install' 
            }
        }
    
    }
}